theme = "solarized_light"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[keys.insert]
C-c = "normal_mode"

[keys.insert.j]
j = "normal_mode" # Maps `jj` to exit insert mode

[keys.select]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
# D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
# C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
# "%" = "match_brackets"
S = "surround_add"
"," = "normal_mode"
y = ["yank_main_selection_to_clipboard"]
d = ["yank_main_selection_to_clipboard", "delete_selection"]

[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
# C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["yank_main_selection_to_clipboard", "delete_selection"]
# S = "surround_add" # Would be nice to be able to do something after this but it isn't chainable
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]
"@" = ["move_prev_word_start", "move_next_word_end", "search_selection", "global_search"]
y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "collapse_selection"]
p = ["paste_clipboard_after", "collapse_selection"]

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
